### ISSUE TITLE
Software license

### ISSUE THREAD

**Issue by LordMand** [x74353/Amphetamine#29]
Hello!

I searched all around for this but couldn't find an answer, so I decided to post it here.
What is the license used for this software? Is it totally free, even for commercial use?
The company I work on is very restrict on software uses, so we need to create a business case for every software that is not "standard". For this documentation, I need a transcript of the software license.
Can anyone help me on this?

Thanks in advance!

**Comment by x74353** [comment]
Apps sold through the Mac App Store are covered by this:
https://www.apple.com/legal/macapps/stdeula/

Since Amphetamine has yet to be distributed outside of the App Store, there is no other licensing agreement available at this time.
