### ISSUE TITLE
Is it supposed to prevent sleep when the lid is closed?

### ISSUE THREAD

**Issue by aristidesfl** [x74353/Amphetamine#30]
Is it supposed to prevent sleep when the lid is closed, or only when it is open?

**Comment by x74353** [comment]
Only when it is open!

Will

**Comment by aristidesfl** [comment]
@x74353 thanks! are there any known apps which prevent sleep when the lid is closed for Sierra?

**Comment by aristidesfl** [comment]
I'm specifically trying to prevent standy by mode temporarily

**Comment by x74353** [comment]
@aristidesfl [InsomniaX](http://semaja2.net/ye-ol-projects/insomniaxinfo/) is the only one I know of, but I've never used it personally.

**Comment by aristidesfl** [comment]
Thank you. I've tried, and it works. Now uninstalled.
