### ISSUE TITLE
Amphetamine ignores mouse event after displaying menu and selecting an option when set to show menu on right click

### ISSUE THREAD

**Issue by bensurtees** [x74353/Amphetamine#31]
Hi, I am the developer of Bartender, and I had a user report an strange issue with Amphetamine.
I use it regularly so was quite surprised, eventually managed to reproduce the issue, and it turns out its a general issue with Amphetamine (even when not using Bartender).

Issue:
After right clicking to show the menu, then selecting say Minutes->5 minutes (any selection from the menu will display the behaviour I think), the next mouse click is ignored.

To Reproduce:
On a system with macOS High Sierra (think Yosemite or newer would display the same behaviour) 
Set Amphetamine to:
Status Bar Icon Click Actions: "Left: Start/end session | Right: Show menu"
Right clicking to show the menu, then selecting say Minutes->5 minutes
Left click on amphetamine menu item

Expected Outcome:
Session would end.

Seen outcome:
Left mouse click is ignored.

If I can be of any assistance with this please let me know.

Ben

**Comment by x74353** [comment]
Fixed with Bartender update (thanks!) Amphetamine 4.0 should address the issue on Amphetamine's side.
